"""Add months field to Debt model

Revision ID: 69721f651558
Revises: 3098a171ae12
Create Date: 2023-12-12 13:36:23.269194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69721f651558'
down_revision = '3098a171ae12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_type', sa.String(length=50), nullable=False),
    sa.Column('principal_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.Column('remaining_balance', sa.Float(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('planned_income', sa.Float(), nullable=False),
    sa.Column('actual_income', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('running_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('date')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('category')

    op.drop_table('transaction_history')
    op.drop_table('income')
    op.drop_table('debt')
    # ### end Alembic commands ###
